name: youtube_player_iframe_example
description: Demonstrates how to use the youtube_player_iframe plugin.
publish_to: none
version: 5.0.0

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
      sdk: flutter
  youtube_player_iframe: ^5.2.0
  go_router: ^14.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
